[project]
name = "agentic-credit-intelligence-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.0",
    "neo4j>=6.0.3",
    "uvicorn>=0.40.0",
]
